# Use container-based infrastructure
language: scala

env:
  matrix:
    - TEST_COMMAND="downloadBitcoind rpcTest/test rpc/coverageReport rpc/coverageAggregate rpc/coveralls"
    - TEST_COMMAND="coreTest/test core/coverageReport core/coverageAggregate core/coveralls"

os: linux
jdk:
  - oraclejdk10
  - openjdk10

scala:
  - 2.13.1

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $PWD/binaries/bitcoind/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

script:
  - sbt scalafmtCheck coverage $TEST_COMMAND
